[project]
name = "mark-twain-ts"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
nodejs = ">=20.9.0,<20.10"
